<?php

use Illuminate\Database\Seeder;

class FlagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('flags')->insert([
			[ "id"=>1, "country"=>'Afghanistan', "flag"=>'flags/af.png'],
			[ "id"=>2, "country"=>'Åland Islands', "flag"=>'flags/ax.png'],
			[ "id"=>3, "country"=>'Albania', "flag"=>'flags/al.png'],
			[ "id"=>4, "country"=>'Algeria', "flag"=>'flags/dz.png'],
			[ "id"=>5, "country"=>'American Samoa', "flag"=>'flags/as.png'],
			[ "id"=>6, "country"=>'Andorra', "flag"=>'flags/ad.png'],
			[ "id"=>7, "country"=>'Angola', "flag"=>'flags/ao.png'],
			[ "id"=>8, "country"=>'Anguilla', "flag"=>'flags/ai.png'],
			[ "id"=>9, "country"=>'Antarctica', "flag"=>'flags/aq.png'],
			[ "id"=>10, "country"=>'Antigua and Barbuda', "flag"=>'flags/ag.png'],
			[ "id"=>11, "country"=>'Argentina', "flag"=>'flags/ar.png'],
			[ "id"=>12, "country"=>'Armenia', "flag"=>'flags/am.png'],
			[ "id"=>13, "country"=>'Aruba', "flag"=>'flags/aw.png'],
			[ "id"=>14, "country"=>'Australia', "flag"=>'flags/au.png'],
			[ "id"=>15, "country"=>'Austria', "flag"=>'flags/at.png'],
			[ "id"=>16, "country"=>'Azerbaijan', "flag"=>'flags/az.png'],
			[ "id"=>17, "country"=>'Bahamas', "flag"=>'flags/bs.png'],
			[ "id"=>18, "country"=>'Bahrain', "flag"=>'flags/bh.png'],
			[ "id"=>19, "country"=>'Bangladesh', "flag"=>'flags/bd.png'],
			[ "id"=>20, "country"=>'Barbados', "flag"=>'flags/bb.png'],
			[ "id"=>21, "country"=>'Belarus', "flag"=>'flags/by.png'],
			[ "id"=>22, "country"=>'Belgium', "flag"=>'flags/be.png'],
			[ "id"=>23, "country"=>'Belize', "flag"=>'flags/bz.png'],
			[ "id"=>24, "country"=>'Benin', "flag"=>'flags/bj.png'],
			[ "id"=>25, "country"=>'Bermuda', "flag"=>'flags/bm.png'],
			[ "id"=>26, "country"=>'Bhutan', "flag"=>'flags/bt.png'],
			[ "id"=>27, "country"=>'Bolivia, Plurinational State of', "flag"=>'flags/bo.png'],
			[ "id"=>28, "country"=>'Bonaire, Sint Eustatius and Saba', "flag"=>'flags/bq.png'],
			[ "id"=>29, "country"=>'Bosnia and Herzegovina', "flag"=>'flags/ba.png'],
			[ "id"=>30, "country"=>'Botswana', "flag"=>'flags/bw.png'],
			[ "id"=>31, "country"=>'Bouvet Island', "flag"=>'flags/bv.png'],
			[ "id"=>32, "country"=>'Brazil', "flag"=>'flags/br.png'],
			[ "id"=>33, "country"=>'British Indian Ocean Territory', "flag"=>'flags/io.png'],
			[ "id"=>34, "country"=>'Brunei Darussalam', "flag"=>'flags/bn.png'],
			[ "id"=>35, "country"=>'Bulgaria', "flag"=>'flags/bg.png'],
			[ "id"=>36, "country"=>'Burkina Faso', "flag"=>'flags/bf.png'],
			[ "id"=>37, "country"=>'Burundi', "flag"=>'flags/bi.png'],
			[ "id"=>38, "country"=>'Cambodia', "flag"=>'flags/kh.png'],
			[ "id"=>39, "country"=>'Cameroon', "flag"=>'flags/cm.png'],
			[ "id"=>40, "country"=>'Canada', "flag"=>'flags/ca.png'],
			[ "id"=>41, "country"=>'Cape Verde', "flag"=>'flags/cv.png'],
			[ "id"=>42, "country"=>'Cayman Islands', "flag"=>'flags/ky.png'],
			[ "id"=>43, "country"=>'Central African Republic', "flag"=>'flags/cf.png'],
			[ "id"=>44, "country"=>'Chad', "flag"=>'flags/td.png'],
			[ "id"=>45, "country"=>'Chile', "flag"=>'flags/cl.png'],
			[ "id"=>46, "country"=>'China', "flag"=>'flags/cn.png'],
			[ "id"=>47, "country"=>'Christmas Island', "flag"=>'flags/cx.png'],
			[ "id"=>48, "country"=>'Cocos (Keeling) Islands', 'flags/cc.png'],
			[ "id"=>49, "country"=>'Colombia', "flag"=>'flags/co.png'],
			[ "id"=>50, "country"=>'Comoros', "flag"=>'flags/km.png'],
			[ "id"=>51, "country"=>'Congo', "flag"=>'flags/cg.png'],
			[ "id"=>52, "country"=>'Congo, the Democratic Republic of the', "flag"=>'flags/cd.png'],
			[ "id"=>53, "country"=>'Cook Islands', "flag"=>'flags/ck.png'],
			[ "id"=>54, "country"=>'Costa Rica', "flag"=>'flags/cr.png'],
			[ "id"=>55, "country"=>'Côte d\'Ivoire', "flag"=>'flags/ci.png'],
			[ "id"=>56, "country"=>'Croatia', "flag"=>'flags/hr.png'],
			[ "id"=>57, "country"=>'Cuba', "flag"=>'flags/cu.png'],
			[ "id"=>58, "country"=>'Curaçao', "flag"=>'flags/cw.png'],
			[ "id"=>59, "country"=>'Cyprus', "flag"=>'flags/cy.png'],
			[ "id"=>60, "country"=>'Czech Republic', "flag"=>'flags/cz.png'],
			[ "id"=>61, "country"=>'Denmark', "flag"=>'flags/dk.png'],
			[ "id"=>62, "country"=>'Djibouti', "flag"=>'flags/dj.png'],
			[ "id"=>63, "country"=>'Dominica', "flag"=>'flags/dm.png'],
			[ "id"=>64, "country"=>'Dominican Republic', "flag"=>'flags/do.png'],
			[ "id"=>65, "country"=>'Ecuador', "flag"=>'flags/ec.png'],
			[ "id"=>66, "country"=>'Egypt', "flag"=>'flags/eg.png'],
			[ "id"=>67, "country"=>'El Salvador', "flag"=>'flags/sv.png'],
			[ "id"=>68, "country"=>'Equatorial Guinea', "flag"=>'flags/gq.png'],
			[ "id"=>69, "country"=>'Eritrea', "flag"=>'flags/er.png'],
			[ "id"=>70, "country"=>'Estonia', "flag"=>'flags/ee.png'],
			[ "id"=>71, "country"=>'Ethiopia', "flag"=>'flags/et.png'],
			[ "id"=>72, "country"=>'Falkland Islands (Malvinas)', "flag"=>'flags/fk.png'],
			[ "id"=>73, "country"=>'Faroe Islands', "flag"=>'flags/fo.png'],
			[ "id"=>74, "country"=>'Fiji', "flag"=>'flags/fj.png'],
			[ "id"=>75, "country"=>'Finland', "flag"=>'flags/fi.png'],
			[ "id"=>76, "country"=>'France', "flag"=>'flags/fr.png'],
			[ "id"=>77, "country"=>'French Guiana', "flag"=>'flags/gf.png'],
			[ "id"=>78, "country"=>'French Polynesia', "flag"=>'flags/pf.png'],
			[ "id"=>79, "country"=>'French Southern Territories', "flag"=>'flags/tf.png'],
			[ "id"=>80, "country"=>'Gabon', "flag"=>'flags/ga.png'],
			[ "id"=>81, "country"=>'Gambia', "flag"=>'flags/gm.png'],
			[ "id"=>82, "country"=>'Georgia', "flag"=>'flags/ge.png'],
			[ "id"=>83, "country"=>'Germany', "flag"=>'flags/de.png'],
			[ "id"=>84, "country"=>'Ghana', "flag"=>'flags/gh.png'],
			[ "id"=>85, "country"=>'Gibraltar', "flag"=>'flags/gi.png'],
			[ "id"=>86, "country"=>'Greece', "flag"=>'flags/gr.png'],
			[ "id"=>87, "country"=>'Greenland', "flag"=>'flags/gl.png'],
			[ "id"=>88, "country"=>'Grenada', "flag"=>'flags/gd.png'],
			[ "id"=>89, "country"=>'Guadeloupe', "flag"=>'flags/gp.png'],
			[ "id"=>90, "country"=>'Guam', "flag"=>'flags/gu.png'],
			[ "id"=>91, "country"=>'Guatemala', "flag"=>'flags/gt.png'],
			[ "id"=>92, "country"=>'Guernsey', "flag"=>'flags/gg.png'],
			[ "id"=>93, "country"=>'Guinea', "flag"=>'flags/gn.png'],
			[ "id"=>94, "country"=>'Guinea-Bissau', 'flags/gw.png'],
			[ "id"=>95, "country"=>'Guyana', "flag"=>'flags/gy.png'],
			[ "id"=>96, "country"=>'Haiti', "flag"=>'flags/ht.png'],
			[ "id"=>97, "country"=>'Heard Island and McDonald Islands', "flag"=>'flags/hm.png'],
			[ "id"=>98, "country"=>'Holy See (Vatican City State)', "flag"=>'flags/va.png'],
			[ "id"=>99, "country"=>'Honduras', "flag"=>'flags/hn.png'],
			[ "id"=>100, "country"=>'Hong Kong', "flag"=>'flags/hk.png'],
			[ "id"=>101, "country"=>'Hungary', "flag"=>'flags/hu.png'],
			[ "id"=>102, "country"=>'Iceland', "flag"=>'flags/is.png'],
			[ "id"=>103, "country"=>'India', "flag"=>'flags/in.png'],
			[ "id"=>104, "country"=>'Indonesia', "flag"=>'flags/id.png'],
			[ "id"=>105, "country"=>'Iran, Islamic Republic of', "flag"=>'flags/ir.png'],
			[ "id"=>106, "country"=>'Iraq', "flag"=>'flags/iq.png'],
			[ "id"=>107, "country"=>'Ireland', "flag"=>'flags/ie.png'],
			[ "id"=>108, "country"=>'Isle of Man', "flag"=>'flags/im.png'],
			[ "id"=>109, "country"=>'Israel', "flag"=>'flags/il.png'],
			[ "id"=>110, "country"=>'Italy', "flag"=>'flags/it.png'],
			[ "id"=>111, "country"=>'Jamaica', "flag"=>'flags/jm.png'],
			[ "id"=>112, "country"=>'Japan', "flag"=>'flags/jp.png'],
			[ "id"=>113, "country"=>'Jersey', "flag"=>'flags/je.png'],
			[ "id"=>114, "country"=>'Jordan', "flag"=>'flags/jo.png'],
			[ "id"=>115, "country"=>'Kazakhstan', "flag"=>'flags/kz.png'],
			[ "id"=>116, "country"=>'Kenya', "flag"=>'flags/ke.png'],
			[ "id"=>117, "country"=>'Kiribati', "flag"=>'flags/ki.png'],
			[ "id"=>118, "country"=>'Korea, Democratic People\'s Republic of', "flag"=>'flags/kp.png'],
			[ "id"=>119, "country"=>'Korea, Republic of', "flag"=>'flags/kr.png'],
			[ "id"=>120, "country"=>'Kuwait', "flag"=>'flags/kw.png'],
			[ "id"=>121, "country"=>'Kyrgyzstan', "flag"=>'flags/kg.png'],
			[ "id"=>122, "country"=>'Lao People\'s Democratic Republic', "flag"=>'flags/la.png'],
			[ "id"=>123, "country"=>'Latvia', "flag"=>'flags/lv.png'],
			[ "id"=>124, "country"=>'Lebanon', "flag"=>'flags/lb.png'],
			[ "id"=>125, "country"=>'Lesotho', "flag"=>'flags/ls.png'],
			[ "id"=>126, "country"=>'Liberia', "flag"=>'flags/lr.png'],
			[ "id"=>127, "country"=>'Libya', "flag"=>'flags/ly.png'],
			[ "id"=>128, "country"=>'Liechtenstein', "flag"=>'flags/li.png'],
			[ "id"=>129, "country"=>'Lithuania', "flag"=>'flags/lt.png'],
			[ "id"=>130, "country"=>'Luxembourg', "flag"=>'flags/lu.png'],
			[ "id"=>131, "country"=>'Macao', "flag"=>'flags/mo.png'],
			[ "id"=>132, "country"=>'Macedonia, the Former Yugoslav Republic of', "flag"=>'flags/mk.png'],
			[ "id"=>133, "country"=>'Madagascar', "flag"=>'flags/mg.png'],
			[ "id"=>134, "country"=>'Malawi', "flag"=>'flags/mw.png'],
			[ "id"=>135, "country"=>'Malaysia', "flag"=>'flags/my.png'],
			[ "id"=>136, "country"=>'Maldives', "flag"=>'flags/mv.png'],
			[ "id"=>137, "country"=>'Mali', "flag"=>'flags/ml.png'],
			[ "id"=>138, "country"=>'Malta', "flag"=>'flags/mt.png'],
			[ "id"=>139, "country"=>'Marshall Islands', "flag"=>'flags/mh.png'],
			[ "id"=>140, "country"=>'Martinique', "flag"=>'flags/mq.png'],
			[ "id"=>141, "country"=>'Mauritania', "flag"=>'flags/mr.png'],
			[ "id"=>142, "country"=>'Mauritius', "flag"=>'flags/mu.png'],
			[ "id"=>143, "country"=>'Mayotte', "flag"=>'flags/yt.png'],
			[ "id"=>144, "country"=>'Mexico', "flag"=>'flags/mx.png'],
			[ "id"=>145, "country"=>'Micronesia, Federated States of', "flag"=>'flags/fm.png'],
			[ "id"=>146, "country"=>'Moldova, Republic of', "flag"=>'flags/md.png'],
			[ "id"=>147, "country"=>'Monaco', "flag"=>'flags/mc.png'],
			[ "id"=>148, "country"=>'Mongolia', "flag"=>'flags/mn.png'],
			[ "id"=>149, "country"=>'Montenegro', "flag"=>'flags/me.png'],
			[ "id"=>150, "country"=>'Montserrat', "flag"=>'flags/ms.png'],
			[ "id"=>151, "country"=>'Morocco', "flag"=>'flags/ma.png'],
			[ "id"=>152, "country"=>'Mozambique', "flag"=>'flags/mz.png'],
			[ "id"=>153, "country"=>'Myanmar', "flag"=>'flags/mm.png'],
			[ "id"=>154, "country"=>'Namibia', "flag"=>'flags/na.png'],
			[ "id"=>155, "country"=>'Nauru', "flag"=>'flags/nr.png'],
			[ "id"=>156, "country"=>'Nepal', "flag"=>'flags/np.png'],
			[ "id"=>157, "country"=>'Netherlands', "flag"=>'flags/nl.png'],
			[ "id"=>158, "country"=>'New Caledonia', "flag"=>'flags/nc.png'],
			[ "id"=>159, "country"=>'New Zealand', "flag"=>'flags/nz.png'],
			[ "id"=>160, "country"=>'Nicaragua', "flag"=>'flags/ni.png'],
			[ "id"=>161, "country"=>'Niger', "flag"=>'flags/ne.png'],
			[ "id"=>162, "country"=>'Nigeria', "flag"=>'flags/ng.png'],
			[ "id"=>163, "country"=>'Niue', "flag"=>'flags/nu.png'],
			[ "id"=>164, "country"=>'Norfolk Island', "flag"=>'flags/nf.png'],
			[ "id"=>165, "country"=>'Northern Mariana Islands', "flag"=>'flags/mp.png'],
			[ "id"=>166, "country"=>'Norway', "flag"=>'flags/no.png'],
			[ "id"=>167, "country"=>'Oman', "flag"=>'flags/om.png'],
			[ "id"=>168, "country"=>'Pakistan', "flag"=>'flags/pk.png'],
			[ "id"=>169, "country"=>'Palau', "flag"=>'flags/pw.png'],
			[ "id"=>170, "country"=>'Palestine, State of', 'flags/ps.png'],
			[ "id"=>171, "country"=>'Panama', "flag"=>'flags/pa.png'],
			[ "id"=>172, "country"=>'Papua New Guinea', "flag"=>'flags/pg.png'],
			[ "id"=>173, "country"=>'Paraguay', "flag"=>'flags/py.png'],
			[ "id"=>174, "country"=>'Peru', "flag"=>'flags/pe.png'],
			[ "id"=>175, "country"=>'Philippines', "flag"=>'flags/ph.png'],
			[ "id"=>176, "country"=>'Pitcairn', "flag"=>'flags/pn.png'],
			[ "id"=>177, "country"=>'Poland', "flag"=>'flags/pl.png'],
			[ "id"=>178, "country"=>'Portugal', "flag"=>'flags/pt.png'],
			[ "id"=>179, "country"=>'Puerto Rico', "flag"=>'flags/pr.png'],
			[ "id"=>180, "country"=>'Qatar', "flag"=>'flags/qa.png'],
			[ "id"=>181, "country"=>'Réunion', "flag"=>'flags/re.png'],
			[ "id"=>182, "country"=>'Romania', "flag"=>'flags/ro.png'],
			[ "id"=>183, "country"=>'Russian Federation', "flag"=>'flags/ru.png'],
			[ "id"=>184, "country"=>'Rwanda', "flag"=>'flags/rw.png'],
			[ "id"=>185, "country"=>'Saint Barthélemy', "flag"=>'flags/bl.png'],
			[ "id"=>186, "country"=>'Saint Helena, Ascension and Tristan da Cunha', "flag"=>'flags/sh.png'],
			[ "id"=>187, "country"=>'Saint Kitts and Nevis', "flag"=>'flags/kn.png'],
			[ "id"=>188, "country"=>'Saint Lucia', "flag"=>'flags/lc.png'],
			[ "id"=>189, "country"=>'Saint Martin (French part)', "flag"=>'flags/mf.png'],
			[ "id"=>190, "country"=>'Saint Pierre and Miquelon', "flag"=>'flags/pm.png'],
			[ "id"=>191, "country"=>'Saint Vincent and the Grenadines', "flag"=>'flags/vc.png'],
			[ "id"=>192, "country"=>'Samoa', "flag"=>'flags/ws.png'],
			[ "id"=>193, "country"=>'San Marino', "flag"=>'flags/sm.png'],
			[ "id"=>194, "country"=>'Sao Tome and Principe', "flag"=>'flags/st.png'],
			[ "id"=>195, "country"=>'Saudi Arabia', "flag"=>'flags/sa.png'],
			[ "id"=>196, "country"=>'Senegal', "flag"=>'flags/sn.png'],
			[ "id"=>197, "country"=>'Serbia', "flag"=>'flags/rs.png'],
			[ "id"=>198, "country"=>'Seychelles', "flag"=>'flags/sc.png'],
			[ "id"=>199, "country"=>'Sierra Leone', "flag"=>'flags/sl.png'],
			[ "id"=>200, "country"=>'Singapore', "flag"=>'flags/sg.png'],
			[ "id"=>201, "country"=>'Sint Maarten (Dutch part)', "flag"=>'flags/sx.png'],
			[ "id"=>202, "country"=>'Slovakia', "flag"=>'flags/sk.png'],
			[ "id"=>203, "country"=>'Slovenia', "flag"=>'flags/si.png'],
			[ "id"=>204, "country"=>'Solomon Islands', "flag"=>'flags/sb.png'],
			[ "id"=>205, "country"=>'Somalia', "flag"=>'flags/so.png'],
			[ "id"=>206, "country"=>'South Africa', "flag"=>'flags/za.png'],
			[ "id"=>207, "country"=>'South Georgia and the South Sandwich Islands', "flag"=>'flags/gs.png'],
			[ "id"=>208, "country"=>'South Sudan', "flag"=>'flags/ss.png'],
			[ "id"=>209, "country"=>'Spain', "flag"=>'flags/es.png'],
			[ "id"=>210, "country"=>'Sri Lanka', "flag"=>'flags/lk.png'],
			[ "id"=>211, "country"=>'Sudan', "flag"=>'flags/sd.png'],
			[ "id"=>212, "country"=>'Suriname', "flag"=>'flags/sr.png'],
			[ "id"=>213, "country"=>'Svalbard and Jan Mayen', "flag"=>'flags/sj.png'],
			[ "id"=>214, "country"=>'Swaziland', "flag"=>'flags/sz.png'],
			[ "id"=>215, "country"=>'Sweden', "flag"=>'flags/se.png'],
			[ "id"=>216, "country"=>'Switzerland', "flag"=>'flags/ch.png'],
			[ "id"=>217, "country"=>'Syrian Arab Republic', "flag"=>'flags/sy.png'],
			[ "id"=>218, "country"=>'Taiwan, Province of China', "flag"=>'flags/tw.png'],
			[ "id"=>219, "country"=>'Tajikistan', "flag"=>'flags/tj.png'],
			[ "id"=>220, "country"=>'Tanzania, United Republic of', "flag"=>'flags/tz.png'],
			[ "id"=>221, "country"=>'Thailand', "flag"=>'flags/th.png'],
			[ "id"=>222, "country"=>'Timor-Leste', "flag"=>'flags/tl.png'],
			[ "id"=>223, "country"=>'Togo', "flag"=>'flags/tg.png'],
			[ "id"=>224, "country"=>'Tokelau', "flag"=>'flags/tk.png'],
			[ "id"=>225, "country"=>'Tonga', "flag"=>'flags/to.png'],
			[ "id"=>226, "country"=>'Trinidad and Tobago', "flag"=>'flags/tt.png'],
			[ "id"=>227, "country"=>'Tunisia', "flag"=>'flags/tn.png'],
			[ "id"=>228, "country"=>'Turkey', "flag"=>'flags/tr.png'],
			[ "id"=>229, "country"=>'Turkmenistan', "flag"=>'flags/tm.png'],
			[ "id"=>230, "country"=>'Turks and Caicos Islands', "flag"=>'flags/tc.png'],
			[ "id"=>231, "country"=>'Tuvalu', "flag"=>'flags/tv.png'],
			[ "id"=>232, "country"=>'Uganda', "flag"=>'flags/ug.png'],
			[ "id"=>233, "country"=>'Ukraine', "flag"=>'flags/ua.png'],
			[ "id"=>234, "country"=>'United Arab Emirates', "flag"=>'flags/ae.png'],
			[ "id"=>235, "country"=>'United Kingdom', "flag"=>'flags/gb.png'],
			[ "id"=>236, "country"=>'United States', "flag"=>'flags/us.png'],
			[ "id"=>237, "country"=>'United States Minor Outlying Islands', "flag"=>'flags/um.png'],
			[ "id"=>238, "country"=>'Uruguay', "flag"=>'flags/uy.png'],
			[ "id"=>239, "country"=>'Uzbekistan', "flag"=>'flags/uz.png'],
			[ "id"=>240, "country"=>'Vanuatu', "flag"=>'flags/vu.png'],
			[ "id"=>241, "country"=>'Venezuela, Bolivarian Republic of', 'flags/ve.png'],
			[ "id"=>242, "country"=>'Viet Nam', "flag"=>'flags/vn.png'],
			[ "id"=>243, "country"=>'Virgin Islands, British', "flag"=>'flags/vg.png'],
			[ "id"=>244, "country"=>'Virgin Islands, U.S.', "flag"=>'flags/vi.png'],
			[ "id"=>245, "country"=>'Wallis and Futuna', "flag"=>'flags/wf.png'],
			[ "id"=>246, "country"=>'Western Sahara', "flag"=>'flags/eh.png'],
			[ "id"=>247, "country"=>'Yemen', "flag"=>'flags/ye.png'],
			[ "id"=>248, "country"=>'Zambia', "flag"=>'flags/zm.png'],
			[ "id"=>249, "country"=>'Zimbabwe', "flag"=>'flags/zw.png']
		]);
    }
}
